backend:
  name: git-gateway
  branch: main

media_folder: "static/images"  # The folder where images will be stored
public_folder: "/images"  # The folder used to display the images

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"  # The folder where your product markdown files are stored
    create: true  # Allows the user to create new entries
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
